version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"  # Optional: WebSocket support
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config
    restart: unless-stopped

  chatbot:
    build:
      context: .
    container_name: meshtastic-chatbot
    env_file:
      - .env
    depends_on:
      - mqtt
    restart: unless-stopped
    volumes:
      - chatbot_data:/data
      
volumes:
  mosquitto_data:
  mosquitto_config:
  chatbot_data: